/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views;

import app.App;
import java.sql.Connection;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import model.*;

/**
 *
 * @author olivier
 */
public class EmployeeView extends javax.swing.JPanel {
    /**
     * We need this parent to show dialog box
     */
    JFrame parent;
    Connection connection;
    ArrayList<Employee> employees;
    
    /**
     * Creates new form EmployeeView
     */
    public EmployeeView(Connection connection, JFrame parent) {
        initComponents();
        this.connection = connection;
        this.parent = parent;
        
        loadEmployee();
    }
    
    private void loadEmployee() {
        if (this.employees != null)
            this.employees.clear();
        
        this.employees =  Employee.getAll(this.connection);
        
        DefaultTableModel model = (DefaultTableModel) employeeTable.getModel();
        
        // Reset the row table
        model.setRowCount(0);
        
        // Add the new rows
        for (Employee employee : employees) {

            Object[] row = new Object[5];
            row[0] = employee.getId();
            row[1] = employee.getFirstName();
            row[2] = employee.getLastName();
            row[3] = employee.getEmail();
            row[4] = employee.getCivility();

            model.addRow(row);
        }
    }
    
    private void addInitialValuesToUpdateForm() {
        if(employeeTable.getSelectedRows().length == 1) {
            int row = employeeTable.getSelectedRow();

            TableModel jtable = employeeTable.getModel();
            
            String id = jtable.getValueAt(row, 0).toString();
            String lastName = jtable.getValueAt(row, 1).toString();
            String firstName = jtable.getValueAt(row, 2).toString();
            String email = jtable.getValueAt(row, 3).toString();
            String civility = jtable.getValueAt(row, 4).toString();

            employeeLastNameTextFieldToUpdate.setText(lastName);
            employeeFirstNameTextFieldToUpdate.setText(firstName);
            employeeEmailTextFieldToUpdate.setText(email);
            employeeCivilityComboBox1.setSelectedItem(civility);
            
        }
    }
    
    private void resetAddForm() {
        employeeLastNameTextField.setText("");
        employeeFirstNameTextField.setText("");
        employeeEmailTextField.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        searchTextField = new javax.swing.JTextField();
        searchBtn = new javax.swing.JButton();
        searchBtn1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        employeeFormContainer = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        addEmployeeTab = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        employeeLastNameTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        employeeFirstNameTextField = new javax.swing.JTextField();
        employeeEmailTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        employeeCivilityComboBox = new javax.swing.JComboBox<>();
        addEmployeeBtn = new javax.swing.JButton();
        updateEmployeeTab = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        employeeCivilityComboBox1 = new javax.swing.JComboBox<>();
        employeeEmailTextFieldToUpdate = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        employeeFirstNameTextFieldToUpdate = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        employeeLastNameTextFieldToUpdate = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        updateEmployeeBtn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        deleteEmployeeBtn = new javax.swing.JButton();
        JScrollPane = new javax.swing.JScrollPane();
        employeeTable = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.BorderLayout());

        jLabel1.setText("Liste des employés");

        searchBtn.setText("Rechercher");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });

        searchBtn1.setText("Effacer");
        searchBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtn1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(searchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchBtn1)))
                .addContainerGap(241, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchBtn)
                    .addComponent(searchBtn1))
                .addContainerGap(68, Short.MAX_VALUE))
        );

        add(jPanel3, java.awt.BorderLayout.PAGE_START);

        jPanel4.setBackground(new java.awt.Color(255, 102, 102));
        jPanel4.setLayout(new java.awt.BorderLayout());

        employeeFormContainer.setPreferredSize(new java.awt.Dimension(500, 477));

        jTabbedPane1.setPreferredSize(new java.awt.Dimension(500, 450));

        jLabel2.setText("Nom");

        employeeLastNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeeLastNameTextFieldActionPerformed(evt);
            }
        });

        jLabel3.setText("Prénom(s)*");

        jLabel4.setText("Email*");

        jLabel5.setText("Civilité*");

        employeeCivilityComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mr", "Mlle", "Mme" }));
        employeeCivilityComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeeCivilityComboBoxActionPerformed(evt);
            }
        });

        addEmployeeBtn.setText("Ajouter");
        addEmployeeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addEmployeeBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout addEmployeeTabLayout = new javax.swing.GroupLayout(addEmployeeTab);
        addEmployeeTab.setLayout(addEmployeeTabLayout);
        addEmployeeTabLayout.setHorizontalGroup(
            addEmployeeTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addEmployeeTabLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(addEmployeeTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2)
                    .addComponent(employeeLastNameTextField)
                    .addComponent(jLabel3)
                    .addComponent(employeeFirstNameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addComponent(employeeEmailTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(employeeCivilityComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addEmployeeBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        addEmployeeTabLayout.setVerticalGroup(
            addEmployeeTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addEmployeeTabLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(employeeLastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(employeeFirstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(employeeEmailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(employeeCivilityComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(addEmployeeBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Ajouter un employé", addEmployeeTab);

        jLabel7.setText("Civilité*");

        employeeCivilityComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mr", "Mlle", "Mme" }));
        employeeCivilityComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeeCivilityComboBox1ActionPerformed(evt);
            }
        });

        jLabel8.setText("Email*");

        jLabel9.setText("Prénom(s)*");

        employeeLastNameTextFieldToUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeeLastNameTextFieldToUpdateActionPerformed(evt);
            }
        });

        jLabel10.setText("Nom");

        updateEmployeeBtn.setText("Sauvegarder les changements");
        updateEmployeeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateEmployeeBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout updateEmployeeTabLayout = new javax.swing.GroupLayout(updateEmployeeTab);
        updateEmployeeTab.setLayout(updateEmployeeTabLayout);
        updateEmployeeTabLayout.setHorizontalGroup(
            updateEmployeeTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updateEmployeeTabLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(updateEmployeeTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel10)
                    .addComponent(employeeLastNameTextFieldToUpdate)
                    .addComponent(jLabel9)
                    .addComponent(employeeFirstNameTextFieldToUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addComponent(employeeEmailTextFieldToUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7)
                    .addComponent(employeeCivilityComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(updateEmployeeBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        updateEmployeeTabLayout.setVerticalGroup(
            updateEmployeeTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updateEmployeeTabLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(employeeLastNameTextFieldToUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(employeeFirstNameTextFieldToUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(employeeEmailTextFieldToUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(employeeCivilityComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(updateEmployeeBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Mettre à jour un employé", updateEmployeeTab);

        employeeFormContainer.add(jTabbedPane1);

        jPanel1.setPreferredSize(new java.awt.Dimension(500, 300));

        jLabel6.setText("Supprimer l'employé selectioné");

        deleteEmployeeBtn.setText("Supprimer");
        deleteEmployeeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteEmployeeBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(deleteEmployeeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(deleteEmployeeBtn)
                .addContainerGap(201, Short.MAX_VALUE))
        );

        employeeFormContainer.add(jPanel1);

        jPanel4.add(employeeFormContainer, java.awt.BorderLayout.LINE_END);

        employeeTable.setAutoCreateRowSorter(true);
        employeeTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Nom", "Prénoms", "Email", "Civilité"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        employeeTable.getTableHeader().setReorderingAllowed(false);
        employeeTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                employeeTableMouseClicked(evt);
            }
        });
        JScrollPane.setViewportView(employeeTable);

        jPanel4.add(JScrollPane, java.awt.BorderLayout.CENTER);

        add(jPanel4, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void addEmployeeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addEmployeeBtnActionPerformed
        String lastName = employeeLastNameTextField.getText();
        String firstName = employeeFirstNameTextField.getText();
        String email = employeeEmailTextField.getText();
        String civility = employeeCivilityComboBox.getSelectedItem().toString();
        
        Employee.create(this.connection, lastName, firstName, civility, email);
        loadEmployee();
    }//GEN-LAST:event_addEmployeeBtnActionPerformed

    private void employeeLastNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeLastNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_employeeLastNameTextFieldActionPerformed

    private void employeeCivilityComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeCivilityComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_employeeCivilityComboBoxActionPerformed

    private void deleteEmployeeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteEmployeeBtnActionPerformed
        if(employeeTable.getSelectedRows().length == 0) {
            JOptionPane.showMessageDialog(parent, "Vous devez selectionner au moins une ligne de la table", "Aucune ligne selectionnée", JOptionPane.ERROR_MESSAGE);
        }else{
            int row = employeeTable.getSelectedRow();

            TableModel jtable = employeeTable.getModel();

            if (employeeTable.getSelectedRows().length == 1) {
                String id = jtable.getValueAt(row, 0).toString();

                Employee.destroy(this.connection, id);
                loadEmployee();
            }
        }
    }//GEN-LAST:event_deleteEmployeeBtnActionPerformed

    private void employeeCivilityComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeCivilityComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_employeeCivilityComboBox1ActionPerformed

    private void employeeLastNameTextFieldToUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeLastNameTextFieldToUpdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_employeeLastNameTextFieldToUpdateActionPerformed

    private void updateEmployeeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateEmployeeBtnActionPerformed
        if(employeeTable.getSelectedRows().length == 0) {
            JOptionPane.showMessageDialog(parent, "Vous devez selectionner au moins une ligne de la table", "Aucune ligne selectionnée", JOptionPane.ERROR_MESSAGE);
        }else{
            int row = employeeTable.getSelectedRow();

            TableModel jtable = employeeTable.getModel();

            if (employeeTable.getSelectedRows().length == 1) {
                String id = jtable.getValueAt(row, 0).toString();

                String lastName= employeeLastNameTextFieldToUpdate.getText();
                String firstName = employeeFirstNameTextFieldToUpdate.getText();
                String email = employeeEmailTextFieldToUpdate.getText();
                String civility = employeeCivilityComboBox1.getSelectedItem().toString();
                
                Employee.update(this.connection, id, lastName, firstName, civility, email);
                
                loadEmployee();
            }
        }
    }//GEN-LAST:event_updateEmployeeBtnActionPerformed

    private void employeeTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_employeeTableMouseClicked
        addInitialValuesToUpdateForm();
    }//GEN-LAST:event_employeeTableMouseClicked

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        ArrayList<Employee> employees = Employee.getByName(this.connection, searchTextField.getText());
        
        DefaultTableModel model = (DefaultTableModel) employeeTable.getModel();
        
        // Reset the row table
        model.setRowCount(0);
        
        // Add the new rows
        for (Employee employee : employees) {

            Object[] row = new Object[5];
            row[0] = employee.getId();
            row[1] = employee.getFirstName();
            row[2] = employee.getLastName();
            row[3] = employee.getEmail();
            row[4] = employee.getCivility();

            model.addRow(row);
        }
    }//GEN-LAST:event_searchBtnActionPerformed

    private void searchBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtn1ActionPerformed
        searchTextField.setText("");
        loadEmployee();
    }//GEN-LAST:event_searchBtn1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane JScrollPane;
    private javax.swing.JButton addEmployeeBtn;
    private javax.swing.JPanel addEmployeeTab;
    private javax.swing.JButton deleteEmployeeBtn;
    private javax.swing.JComboBox<String> employeeCivilityComboBox;
    private javax.swing.JComboBox<String> employeeCivilityComboBox1;
    private javax.swing.JTextField employeeEmailTextField;
    private javax.swing.JTextField employeeEmailTextFieldToUpdate;
    private javax.swing.JTextField employeeFirstNameTextField;
    private javax.swing.JTextField employeeFirstNameTextFieldToUpdate;
    private javax.swing.JPanel employeeFormContainer;
    private javax.swing.JTextField employeeLastNameTextField;
    private javax.swing.JTextField employeeLastNameTextFieldToUpdate;
    private javax.swing.JTable employeeTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton searchBtn;
    private javax.swing.JButton searchBtn1;
    private javax.swing.JTextField searchTextField;
    private javax.swing.JButton updateEmployeeBtn;
    private javax.swing.JPanel updateEmployeeTab;
    // End of variables declaration//GEN-END:variables
}
