/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views;

import java.sql.Connection;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.text.StyledEditorKit;
import model.Place;
import com.alexandriasoftware.swing.*;
import javax.swing.InputVerifier;
import javax.swing.JComponent;
import javax.swing.JTextField;
import javax.swing.event.*;

/**
 *
 * @author olivier
 */
public class PlaceView extends javax.swing.JPanel {
    ArrayList<Place> places;
    Connection connection;
    Place selectedPlace;
    
    boolean reseted = false, updateReseted = false;
    
    JFrame parent;
    /**
     * Creates new form PlaceView
     */
    public PlaceView(Connection connection,JFrame parent) {
        this.connection = connection;
        this.parent = parent;
        initComponents();
        loadPlaces();
    }

    private void loadPlaces() {
        if (this.places != null) {
            this.places.clear();
        }

        this.places = Place.getAll(connection);

        DefaultTableModel model = (DefaultTableModel) placeTable.getModel();

        model.setRowCount(0);

        for (Place place : places) {

            Object[] row = new Object[4];
            row[0] = place.getId();
            row[1] = place.getName();
            row[2] = place.getProvince();

            model.addRow(row);
        }
    }
    
    private void resetCreateForm() {
        placeNameTextField.setText("");
        provinceComboBox.setSelectedIndex(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        placeFormContainer = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        deletePlaceBtn = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        placeNameTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        provinceComboBox = new javax.swing.JComboBox<>();
        createPlaceBtn = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        placeNameToUpdateTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        provinceToUpdateComboBox = new javax.swing.JComboBox<>();
        updatePlaceBtn = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        placeTable = new javax.swing.JTable();

        setBackground(new java.awt.Color(240, 240, 240));
        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(240, 240, 240));
        jPanel1.setPreferredSize(new java.awt.Dimension(815, 80));

        jLabel2.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel2.setText("Liste des lieux");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(884, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel2)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBackground(new java.awt.Color(240, 240, 240));
        jPanel2.setLayout(new java.awt.BorderLayout());

        placeFormContainer.setBackground(new java.awt.Color(240, 240, 240));
        placeFormContainer.setPreferredSize(new java.awt.Dimension(500, 382));
        placeFormContainer.setLayout(new java.awt.BorderLayout());

        jPanel3.setBackground(new java.awt.Color(240, 240, 240));

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N
        jLabel1.setText("Supprimer le lieu selectionné");

        deletePlaceBtn.setBackground(new java.awt.Color(255, 0, 51));
        deletePlaceBtn.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N
        deletePlaceBtn.setForeground(new java.awt.Color(255, 255, 255));
        deletePlaceBtn.setText("Supprimer");
        deletePlaceBtn.setEnabled(false);
        deletePlaceBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deletePlaceBtn.setMargin(new java.awt.Insets(5, 14, 5, 14));
        deletePlaceBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletePlaceBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(deletePlaceBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(198, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deletePlaceBtn)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        placeFormContainer.add(jPanel3, java.awt.BorderLayout.PAGE_END);

        jTabbedPane1.setBackground(new java.awt.Color(240, 240, 240));
        jTabbedPane1.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N

        jPanel4.setBackground(new java.awt.Color(240, 240, 240));

        jLabel3.setText("Désignation");

        placeNameTextField.setInputVerifier(new JInputValidator(placeNameTextField, true,true) {
            @Override
            protected Validation getValidation(JComponent input, JInputValidatorPreferences preferences){
                if(placeNameTextField.getText().length() < 3 && !reseted){
                    return new Validation(Validation.Type.DANGER, "Too short", preferences);
                }
                return new Validation(Validation.Type.NONE, "", preferences);
            }
        });
        placeNameTextField.getDocument().addDocumentListener(new DocumentListener(){
            public void changedUpdate(DocumentEvent e){
                reseted = false;
                enableSubmit();
            }
            public void removeUpdate(DocumentEvent e){
                reseted = false;
                enableSubmit();
            }
            public void insertUpdate(DocumentEvent e){
                reseted = false;
                enableSubmit();
            }
        });
        placeNameTextField.setPreferredSize(new java.awt.Dimension(64, 35));

        jLabel4.setText("Province");

        provinceComboBox.setBackground(new java.awt.Color(255, 255, 254));
        provinceComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Antananarivo", "Fianarantsoa", "Antsiranana","Mahajanga","Toamasina","Toliara" }));
        provinceComboBox.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        provinceComboBox.setPreferredSize(new java.awt.Dimension(72, 35));

        createPlaceBtn.setBackground(new java.awt.Color(0, 51, 255));
        createPlaceBtn.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N
        createPlaceBtn.setForeground(new java.awt.Color(255, 255, 255));
        createPlaceBtn.setText("Ajouter");
        createPlaceBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        createPlaceBtn.setMargin(new java.awt.Insets(5, 14, 5, 14));
        createPlaceBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createPlaceBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3)
                            .addComponent(placeNameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4)
                            .addComponent(provinceComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(createPlaceBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(placeNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(provinceComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(createPlaceBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 189, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        jTabbedPane1.addTab("Ajouter un nouveau lieu", jPanel4);

        jPanel5.setBackground(new java.awt.Color(240, 240, 240));

        jPanel6.setBackground(new java.awt.Color(240, 240, 240));

        jLabel5.setText("Désignation");

        placeNameToUpdateTextField.setInputVerifier(new JInputValidator(placeNameToUpdateTextField, true,true) {
            @Override
            protected Validation getValidation(JComponent input, JInputValidatorPreferences preferences){
                if(placeNameToUpdateTextField.getText().length() < 3 && !reseted){
                    return new Validation(Validation.Type.DANGER, "Too short", preferences);
                }
                return new Validation(Validation.Type.NONE, "", preferences);
            }
        });
        placeNameToUpdateTextField.getDocument().addDocumentListener(new DocumentListener(){
            public void changedUpdate(DocumentEvent e){
                updateReseted = false;
                enableUpdateSubmit();
            }
            public void removeUpdate(DocumentEvent e){
                updateReseted = false;
                enableUpdateSubmit();
            }
            public void insertUpdate(DocumentEvent e){
                updateReseted = false;
                enableUpdateSubmit();
            }
        });
        placeNameToUpdateTextField.setPreferredSize(new java.awt.Dimension(64, 35));

        jLabel6.setText("Province");

        provinceToUpdateComboBox.setBackground(new java.awt.Color(255, 255, 254));
        provinceToUpdateComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Antananarivo", "Fianarantsoa", "Antsiranana","Mahajanga","Toamasina","Toliara" }));
        provinceToUpdateComboBox.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        provinceToUpdateComboBox.setPreferredSize(new java.awt.Dimension(72, 35));

        updatePlaceBtn.setBackground(new java.awt.Color(0, 51, 255));
        updatePlaceBtn.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N
        updatePlaceBtn.setForeground(new java.awt.Color(255, 255, 255));
        updatePlaceBtn.setText("Sauvegarder les modifications");
        updatePlaceBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        updatePlaceBtn.setMargin(new java.awt.Insets(5, 14, 5, 14));
        updatePlaceBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatePlaceBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5)
                    .addComponent(placeNameToUpdateTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6)
                    .addComponent(provinceToUpdateComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(updatePlaceBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(placeNameToUpdateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(provinceToUpdateComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(updatePlaceBtn)
                .addContainerGap(72, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jSeparator2))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );

        jTabbedPane1.addTab("Modifier un lieu", jPanel5);

        placeFormContainer.add(jTabbedPane1, java.awt.BorderLayout.CENTER);

        jPanel2.add(placeFormContainer, java.awt.BorderLayout.LINE_END);

        jScrollPane1.setBackground(new java.awt.Color(240, 240, 240));

        placeTable.setAutoCreateRowSorter(true);
        placeTable.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        placeTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Désignation", "Province"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        placeTable.setFocusable(false);
        placeTable.setGridColor(new java.awt.Color(255, 255, 255));
        placeTable.setIntercellSpacing(new java.awt.Dimension(3, 0));
        placeTable.setRowHeight(50);
        placeTable.setSelectionBackground(new java.awt.Color(102, 102, 255));
        placeTable.setSelectionForeground(new java.awt.Color(255, 255, 255));
        placeTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        placeTable.setShowVerticalLines(true);
        placeTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                placeTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(placeTable);
        placeTable.getSelectionModel().addListSelectionListener(new ListSelectionListener(){
            public void valueChanged(ListSelectionEvent event){
                if(!event.getValueIsAdjusting() && placeTable.getSelectedRow() != -1){
                    deletePlaceBtn.setEnabled(true);
                }else{
                    deletePlaceBtn.setEnabled(false);
                }
            }
        });
        if (placeTable.getColumnModel().getColumnCount() > 0) {
            placeTable.getColumnModel().getColumn(0).setMaxWidth(50);
        }

        jPanel2.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        add(jPanel2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void deletePlaceBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletePlaceBtnActionPerformed
        if (placeTable.getSelectedRows().length == 0) {
            JOptionPane.showMessageDialog(parent, "Vous devez selectionner au moins une ligne de la table", "Aucune ligne selectionnée", JOptionPane.ERROR_MESSAGE);
        } else {
            if (placeTable.getSelectedRows().length == 1) {
                Place.destroy(this.connection, selectedPlace.getId());

                loadPlaces();
                selectedPlace = null;
            }
        }
    }//GEN-LAST:event_deletePlaceBtnActionPerformed

    private void createPlaceBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createPlaceBtnActionPerformed
        String name = placeNameTextField.getText();
        String province = provinceComboBox.getSelectedItem().toString();
        
        Place.create(connection, name, province);
        loadPlaces();
    }//GEN-LAST:event_createPlaceBtnActionPerformed

    private void placeTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_placeTableMouseClicked
        if (placeTable.getSelectedRows().length == 1) {
            int row = placeTable.getSelectedRow();

            TableModel jtable = placeTable.getModel();

            Integer id = Integer.parseInt(jtable.getValueAt(row, 0).toString());
            selectedPlace = Place.getOneById(connection, id);

            placeNameToUpdateTextField.setText(selectedPlace.getName());

            provinceToUpdateComboBox.setSelectedItem(selectedPlace.getProvince());

        }
    }//GEN-LAST:event_placeTableMouseClicked

    private void updatePlaceBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatePlaceBtnActionPerformed
        if (placeTable.getSelectedRows().length == 0) {
            JOptionPane.showMessageDialog(parent, "Vous devez selectionner au moins une ligne de la table", "Aucune ligne selectionnée", JOptionPane.ERROR_MESSAGE);
        } else {
            if (placeTable.getSelectedRows().length == 1) {
                String name = placeNameToUpdateTextField.getText();
                String province = provinceToUpdateComboBox.getSelectedItem().toString();
                
                Place.update(this.connection, selectedPlace.getId(), name, province);

                loadPlaces();
                selectedPlace = null;
            }
        }
    }//GEN-LAST:event_updatePlaceBtnActionPerformed
    
    private void enableSubmit() {
        boolean isPlaceNameValid = placeNameTextField.getText() != "" && placeNameTextField.getText().length() > 2;

        if (isPlaceNameValid) {
            createPlaceBtn.setEnabled(true);
        } else {
            createPlaceBtn.setEnabled(false);
        }
    }
    
    private void enableUpdateSubmit() {
        boolean isPlaceNameValid = placeNameToUpdateTextField.getText() != "" && placeNameToUpdateTextField.getText().length() > 2;

        if (isPlaceNameValid) {
            updatePlaceBtn.setEnabled(true);
        } else {
            updatePlaceBtn.setEnabled(false);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createPlaceBtn;
    private javax.swing.JButton deletePlaceBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel placeFormContainer;
    private javax.swing.JTextField placeNameTextField;
    private javax.swing.JTextField placeNameToUpdateTextField;
    private javax.swing.JTable placeTable;
    private javax.swing.JComboBox<String> provinceComboBox;
    private javax.swing.JComboBox<String> provinceToUpdateComboBox;
    private javax.swing.JButton updatePlaceBtn;
    // End of variables declaration//GEN-END:variables
}
